# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Adarsh Srivastava's Blog"

description:        "Adarsh Srivastava's personal blog and portfolio."

author:             
#  facebook:         adarsh0112
#  twitter:          adarshs_
  github:           adrshsrvstv
  linkedin:         adrshsrvstv
  email:            hi@adrshsrvstv.com
  goodreads:        adrshsrvstv

copyright:
  year:             2020
  name:             Adarsh Srivastava

# Google-analytics
google-analytics:
  id:               "UA-138767520-2"

google_site_verification: "sf3_hCQjOCI7VfUHF6a5NZOZceWsoOpZypi7Mntj7II"

lang:               "en_US"
# Disqus
# disqus:
#   id:               "kiko-plus"

# URL
url:                "https://adrshsrvstv.com" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Kolkata
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           10
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "Hi"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Projects"
    url:            "/projects"
  - name:           "resumé"
    url:            "/assets/docs/resume.pdf"
  - name:           "books"
    url:            "https://www.goodreads.com/adrshsrvstv"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin
  - jemoji

exclude:            [vendor]
